### ISSUE TITLE
When using with Next.js I am getting "window" is not defined even though I am running on client side

### ISSUE THREAD

**Issue by bchurlinov** [browser-update/browser-update#524]
As mentioned in the title I am having issues running this plugin with Next.js

Things I did:
- Installed via "yarn add browser-update"
- Imported the plugin
- Tried adding it in the "_app.tsx" by checking if the window object is not undefined and also in useEffect ( both didn't work ).
- I tried adding this in another page, still the same result.

Someone else implemented this with Next.js ?

**Comment by josselex** [comment]
In which line do you get the error?

**Comment by bchurlinov** [comment]
This is the error from the console:

ReferenceError: window is not defined
    at Object.<anonymous> (C:\<PROJECT_NAME>\node_modules\browser-update\update.npm.full.js:230:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)

**Comment by chapmanio** [comment]
I had the issue as well @bchurlinov, you _could_ solve it by [dynamically importing](https://nextjs.org/docs/advanced-features/dynamic-import) the module in the `useEffect` as follows:

``` js
useEffect(() => {
  const loadBrowserUpdate = async () => {
    const browserUpdate = (await import('browser-update')).default;

    browserUpdate({
      required: { e: -4, f: -3, o: -3, s: -1, c: -3 },
      insecure: true,
      unsupported: true,
      api: 2021.03,
      reminder: 0,
      reminderClosed: 24,
    });
  };

  loadBrowserUpdate();
}, []);
```

**But** some of the browsers you (and I) want this to appear in won't support dynamically loading modules, so the dirty way is to use the script and `dangerouslySetInnerHTML` option...


```js
<script
  dangerouslySetInnerHTML={{
    __html: `
      var $buoop = {required:{e:-4,f:-3,o:-3,s:-1,c:-3},insecure:true,unsupported:true,api:2021.03 };
      function $buo_f(){
      var e = document.createElement("script");
      e.src = "//browser-update.org/update.min.js";
      document.body.appendChild(e);
      };
      try {document.addEventListener("DOMContentLoaded", $buo_f,false)}
      catch(e){window.attachEvent("onload", $buo_f)}
    `,
  }}
/>
```

This works for me and it shows up in IE11, etc as expected.

**Comment by josselex** [comment]
Do you know if there is a way we could fix this from our side?
